### PR TITLE
Updating the registration to work with the new shadow root DOM

### PR DESCRIPTION
**Pull request by sergejbog**
The recent changes in the reddit UI have implemented the usage of shadow DOM, which broke the original script. I have updated the script to account for these changes.

The only part I did not implement which was in the original code was the final "submit_err". Instead I only have a generic error if the page did not change after 3 seconds, because I was not able to replicate the "submit_err" message.

### CODE REVIEW

**Comment by cubicbyte** [comment]
Thanks for the PR!

I'll accept it after checks

**Comment by InfinityExists** [comment]
Attempted using the script after this change. After solving the captcha it tries to hit "continue" and the browser crashes

2024-04-17 20:44:44 DEBUG Submitting registration
2024-04-17 20:44:55 DEBUG Quitting driver
2024-04-17 20:44:59 ERROR Submit failed
2024-04-17 20:44:59 ERROR An error occurred during account creation. Trying again...

**Comment by sergejbog** [comment]
Hmmm, that is strange, I didn't encounter any of that when testing it out yesterday. Can you tell me on how I can reproduce it? Were you using tor, or a proxy or just your local internet? Also, did the click go through and then it failed, or it failed before even registering the account?

**Comment by InfinityExists** [comment]
> Hmmm, that is strange, I didn't encounter any of that when testing it out yesterday. Can you tell me on how I can reproduce it? Were you using tor, or a proxy or just your local internet? Also, did the click go through and then it failed, or it failed before even registering the account?

My local internet. The click didn't even go through. The button to register changed shades and then the browser crashes. Let me try to update the supporting resources/reinstall them. 

EDIT: I updated Chrome and now it's working. Thanks!

**Pull request merged**
